//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLIANCE_DETAIL_INFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLIANCE_DETAIL_INFORMATION()
        {
            this.APPLIANCE_LABORATORY = new HashSet<APPLIANCE_LABORATORY>();
            this.APPLIANCECOLLECTION = new HashSet<APPLIANCECOLLECTION>();
        }
    
        public string ID { get; set; }
        public string BAR_CODE_NUM { get; set; }
        public string APPLIANCE_NAME { get; set; }
        public string VERSION { get; set; }
        public string FORMAT { get; set; }
        public string FACTORY_NUM { get; set; }
        public Nullable<decimal> NUM { get; set; }
        public string ATTACHMENT { get; set; }
        public string APPEARANCE_STATUS { get; set; }
        public string MAKE_ORGANIZATION { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> END_PLAN_DATE { get; set; }
        public string ORDER_TASK_INFORMATIONID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string APPLIANCE_RECIVE { get; set; }
        public string APPLIANCE_PROGRESS { get; set; }
        public string ISOVERDUE { get; set; }
        public string OVERDUE { get; set; }
        public string STORAGEINSTRUCTIONS { get; set; }
        public string STORAGEINSTRUCTI_STATU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLIANCE_LABORATORY> APPLIANCE_LABORATORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLIANCECOLLECTION> APPLIANCECOLLECTION { get; set; }
        public virtual ORDER_TASK_INFORMATION ORDER_TASK_INFORMATION { get; set; }
    }
}
