//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLIANCE_LABORATORY
    {
        public string ID { get; set; }
        public string UNDERTAKE_LABORATORYID { get; set; }
        public string APPLIANCE_DETAIL_INFORMATIONID { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public string RECEIVEPERSON { get; set; }
        public Nullable<System.DateTime> RECEIVETIME { get; set; }
        public string BACKPERSON { get; set; }
        public Nullable<System.DateTime> BACKTIME { get; set; }
        public string DISTRIBUTIONPERSON { get; set; }
        public Nullable<System.DateTime> DISTRIBUTIONTIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string ORDER_STATUS { get; set; }
        public string EQUIPMENT_STATUS_VALUUMN { get; set; }
        public string RETURN_INSTRUCTIONS { get; set; }
        public string ISRECEIVE { get; set; }
        public string RECYCLING { get; set; }
    
        public virtual APPLIANCE_DETAIL_INFORMATION APPLIANCE_DETAIL_INFORMATION { get; set; }
        public virtual PREPARE_SCHEME PREPARE_SCHEME { get; set; }
    }
}
