//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSS_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CROSS_HEAD()
        {
            this.CROSS_COS = new HashSet<CROSS_COS>();
            this.CROSS_FREQUENCY_POWER_FACTOR = new HashSet<CROSS_FREQUENCY_POWER_FACTOR>();
            this.CROSS_SIN = new HashSet<CROSS_SIN>();
            this.CROSS_VOLTAGE_CURRENT = new HashSet<CROSS_VOLTAGE_CURRENT>();
        }
    
        public string ID { get; set; }
        public string TYPE { get; set; }
        public string VALUE { get; set; }
        public string VALUE_UNIT { get; set; }
        public string GRADE_VALUE { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CROSS_COS> CROSS_COS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CROSS_FREQUENCY_POWER_FACTOR> CROSS_FREQUENCY_POWER_FACTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CROSS_SIN> CROSS_SIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CROSS_VOLTAGE_CURRENT> CROSS_VOLTAGE_CURRENT { get; set; }
    }
}
