//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_UPLOADER
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PATH { get; set; }
        public string FULLPATH { get; set; }
        public string SUFFIX { get; set; }
        public Nullable<decimal> SIZE { get; set; }
        public string REMARK { get; set; }
        public string NAME2 { get; set; }
        public string PATH2 { get; set; }
        public string FULLPATH2 { get; set; }
        public string SUFFIX2 { get; set; }
        public Nullable<decimal> SIZE2 { get; set; }
        public string REMARK2 { get; set; }
        public string STATE2 { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public string CONCLUSION { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        public virtual PREPARE_SCHEME PREPARE_SCHEME { get; set; }
    }
}
