//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class METERING_STANDARD_DEVICE_CHECK
    {
        public string ID { get; set; }
        public string CERTIFICATE_NUM { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<System.DateTime> VALID_TO { get; set; }
        public string METERING_STANDARD_DEVICEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string CERTIFICATEUNIT { get; set; }
        public Nullable<decimal> GROUPS { get; set; }
    
        public virtual METERING_STANDARD_DEVICE METERING_STANDARD_DEVICE { get; set; }
    }
}
