//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class METERING_STANDARD_DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public METERING_STANDARD_DEVICE()
        {
            this.ALLOWABLE_ERROR = new HashSet<ALLOWABLE_ERROR>();
            this.METERING_STANDARD_DEVICE_CHECK = new HashSet<METERING_STANDARD_DEVICE_CHECK>();
            this.PREPARE_SCHEME = new HashSet<PREPARE_SCHEME>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TEST_RANGE { get; set; }
        public string FACTORY_NUM { get; set; }
        public string CATEGORY { get; set; }
        public string STATUS { get; set; }
        public string UNDERTAKE_LABORATORYID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string XINGHAO { get; set; }
        public string THESUPERIOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLOWABLE_ERROR> ALLOWABLE_ERROR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METERING_STANDARD_DEVICE_CHECK> METERING_STANDARD_DEVICE_CHECK { get; set; }
        public virtual UNDERTAKE_LABORATORY UNDERTAKE_LABORATORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREPARE_SCHEME> PREPARE_SCHEME { get; set; }
    }
}
