//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_TASK_INFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_TASK_INFORMATION()
        {
            this.APPLIANCE_DETAIL_INFORMATION = new HashSet<APPLIANCE_DETAIL_INFORMATION>();
        }
    
        public string ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string ACCEPT_ORGNIZATION { get; set; }
        public string INSPECTION_ENTERPRISE { get; set; }
        public string INSPECTION_ENTERPRISE_ADDRESS { get; set; }
        public string INSPECTION_ENTERPRISE_POST { get; set; }
        public string CONTACTS { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string FAX { get; set; }
        public string CERTIFICATE_ENTERPRISE { get; set; }
        public string CERTIFICATE_ENTERPRISE_ADDRESS { get; set; }
        public string CERTIFICATE_ENTERPRISE_POST { get; set; }
        public string CONTACTS2 { get; set; }
        public string CONTACT_PHONE2 { get; set; }
        public string FAX2 { get; set; }
        public string CUSTOMER_SPECIFIC_REQUIREMENTS { get; set; }
        public string ORDER_STATUS { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLIANCE_DETAIL_INFORMATION> APPLIANCE_DETAIL_INFORMATION { get; set; }
    }
}
