//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVERALL_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OVERALL_TABLE()
        {
            this.AC_VOLTAGE_CURRENT = new HashSet<AC_VOLTAGE_CURRENT>();
            this.ACTIVE_POWER = new HashSet<ACTIVE_POWER>();
            this.DC_CURRENT_OUTPUT = new HashSet<DC_CURRENT_OUTPUT>();
            this.DC_VOLTAGE_CURRENT_MEASURE = new HashSet<DC_VOLTAGE_CURRENT_MEASURE>();
            this.DC_VOLTAGE_CURRENT_MEASURE_CH = new HashSet<DC_VOLTAGE_CURRENT_MEASURE_CH>();
            this.DC_VOLTAGE_MEASURE_NO_INDEX = new HashSet<DC_VOLTAGE_MEASURE_NO_INDEX>();
            this.DC_VOLTAGE_OUTPUT = new HashSet<DC_VOLTAGE_OUTPUT>();
            this.FREQUENCY = new HashSet<FREQUENCY>();
            this.PHASE = new HashSet<PHASE>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string KVALUE { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_VOLTAGE_CURRENT> AC_VOLTAGE_CURRENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVE_POWER> ACTIVE_POWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_CURRENT_OUTPUT> DC_CURRENT_OUTPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_VOLTAGE_CURRENT_MEASURE> DC_VOLTAGE_CURRENT_MEASURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_VOLTAGE_CURRENT_MEASURE_CH> DC_VOLTAGE_CURRENT_MEASURE_CH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_VOLTAGE_MEASURE_NO_INDEX> DC_VOLTAGE_MEASURE_NO_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_VOLTAGE_OUTPUT> DC_VOLTAGE_OUTPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FREQUENCY> FREQUENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHASE> PHASE { get; set; }
    }
}
