//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTTEMPLET
    {
        public string ID { get; set; }
        public string RULEID { get; set; }
        public string SCHEMEID { get; set; }
        public string HTMLVALUE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        public virtual RULE RULE { get; set; }
        public virtual SCHEME SCHEME { get; set; }
    }
}
