//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_ITEM_FORMAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_ITEM_FORMAT()
        {
            this.SCHEME_RULE = new HashSet<SCHEME_RULE>();
            this.TABLE_BODY_XY = new HashSet<TABLE_BODY_XY>();
            this.TABLE_HEAD_XY = new HashSet<TABLE_HEAD_XY>();
        }
    
        public string ID { get; set; }
        public Nullable<decimal> ROW_COUNT { get; set; }
        public Nullable<decimal> COLUMN_COUNT { get; set; }
        public Nullable<decimal> CHANNEL_NUMBER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEME_RULE> SCHEME_RULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_BODY_XY> TABLE_BODY_XY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_HEAD_XY> TABLE_HEAD_XY { get; set; }
    }
}
