//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSMITER_SIN
    {
        public string ID { get; set; }
        public string TEST_QUANTITY { get; set; }
        public string GRADE { get; set; }
        public string TEST_POINT { get; set; }
        public string TEST_POINT_UNIT { get; set; }
        public string SIN { get; set; }
        public string SIN_UNIT { get; set; }
        public string TWO_INPUT_STANDARD_VALUE { get; set; }
        public string TWO_INPUT_STANDARD_VALUE_UNIT { get; set; }
        public string STANDARD_OUTPUT_VALUE { get; set; }
        public string STANDARD_OUTPUT_VALUE_UNIT { get; set; }
        public string ACTUAL_OUTPUT_VALUE { get; set; }
        public string ACTUAL_OUTPUT_VALUE_UNIT { get; set; }
        public string REFERENCE_ERROR { get; set; }
        public string REFERENCE_ERROR_UNIT { get; set; }
        public string TRANSMITTER_HEADID { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        public virtual TRANSMITTER_HEAD TRANSMITTER_HEAD { get; set; }
    }
}
