//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSMITTER_RANGE
    {
        public string ID { get; set; }
        public string TEST_QUANTITY { get; set; }
        public string INPUT_START { get; set; }
        public string INPUT_START_UNIT { get; set; }
        public string INPUT_END { get; set; }
        public string INPUT_END_UNIT { get; set; }
        public string OUTPUT_START { get; set; }
        public string OUTPUT_START_UNIT { get; set; }
        public string OUTPUT_END { get; set; }
        public string OUTPUT_END_UNIT { get; set; }
        public string SORT { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    }
}
