//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSMITTER_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSMITTER_HEAD()
        {
            this.TRANSMITER_SIN = new HashSet<TRANSMITER_SIN>();
            this.TRANSMITTER_COS = new HashSet<TRANSMITTER_COS>();
            this.TRANSMITTER_FREQUENCY_PHASE = new HashSet<TRANSMITTER_FREQUENCY_PHASE>();
            this.TRANSMITTER_POWER_FACTOR = new HashSet<TRANSMITTER_POWER_FACTOR>();
        }
    
        public string ID { get; set; }
        public string 类型 { get; set; }
        public string 变送器输入开始 { get; set; }
        public string 变送器输入开始单位 { get; set; }
        public string 变送器输入结束 { get; set; }
        public string 变送器输入结束单位 { get; set; }
        public string 通道 { get; set; }
        public string Un { get; set; }
        public string Un单位 { get; set; }
        public string In { get; set; }
        public string In单位 { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSMITER_SIN> TRANSMITER_SIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSMITTER_COS> TRANSMITTER_COS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSMITTER_FREQUENCY_PHASE> TRANSMITTER_FREQUENCY_PHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSMITTER_POWER_FACTOR> TRANSMITTER_POWER_FACTOR { get; set; }
    }
}
