//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNCERTAINTYTABLE
    {
        public string NOTE { get; set; }
        public string INDEX2UNIT { get; set; }
        public string INDEX2 { get; set; }
        public string INDEX1UNIT { get; set; }
        public string INDEX1 { get; set; }
        public string ENDUNITFREQUENCY { get; set; }
        public string ENDRELATIONSHIPFREQUENCY { get; set; }
        public string THERELATIONSHIPFREQUENCY { get; set; }
        public string THEUNITFREQUENCY { get; set; }
        public string THEFREQUENCY { get; set; }
        public string ENDRELATIONSHIP { get; set; }
        public string ENDUNIT { get; set; }
        public string ENDRANGESCOPE { get; set; }
        public string THERELATIONSHIP { get; set; }
        public string THEUNIT { get; set; }
        public string THERANGESCOPE { get; set; }
        public string KVALE { get; set; }
        public string THEERRODISTRIBUTION { get; set; }
        public string ERRORLIMITUNIT { get; set; }
        public string ERRORLIMITS { get; set; }
        public string ERRORSOURCES { get; set; }
        public string ASSESSMENTITEM { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string METERING_STANDARD_DEVICEID { get; set; }
        public string ID { get; set; }
    
        public virtual METERING_STANDARD_DEVICE METERING_STANDARD_DEVICE { get; set; }
    }
}
