//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBIAOZHUNLIANGCHUANGONGZHUO
    {
        public string ID { get; set; }
        public string WEITUODANWEI { get; set; }
        public string SUOSHUDANWEI { get; set; }
        public string ZHENGSHUDANWEI { get; set; }
        public string SONGJIANDANWEI { get; set; }
        public string SHOULIDANWEI { get; set; }
        public string CHUCHANGRIQI { get; set; }
        public string QIJUMINGCHENG { get; set; }
        public string SHENGCHANCHANGJIA { get; set; }
        public string QIJUXINGHAO { get; set; }
        public string QIJUGUIGE { get; set; }
        public string CHUCHANGBIANHAO { get; set; }
        public Nullable<decimal> SHULIANG { get; set; }
        public Nullable<System.DateTime> SONGJIANRIQI { get; set; }
        public string SONGJIANREN { get; set; }
        public string JIESHOUREN { get; set; }
        public string SHIYANSHI { get; set; }
        public Nullable<System.DateTime> SHIYANSHIJIESHOUSHIJIAN { get; set; }
        public Nullable<System.DateTime> JIANDINGRIQI { get; set; }
        public string JIANDINGXIAOZHUNYUAN { get; set; }
        public string HEYANYUAN { get; set; }
        public string ZHENGSHUHAOLEIBIE { get; set; }
        public string ZHENGSHUBAOGAOBIANHAO { get; set; }
        public string ZHENGSHULEIBIE { get; set; }
        public string BAOGAOLEIBIE { get; set; }
        public string SHOUQUANZIZHI { get; set; }
        public string QIJUZHUANGTAI { get; set; }
        public Nullable<System.DateTime> YOUXIAOQIZHI { get; set; }
        public Nullable<System.DateTime> BAOGAOSHENPITONGGUORIQI { get; set; }
        public string MOCHONGCHANGSHU { get; set; }
        public Nullable<decimal> SONGJIANYUEDU { get; set; }
        public string JIANDINGSHIJIAN { get; set; }
        public string JIANDINGYUEDU { get; set; }
        public string BAOGAOSHIJIAN { get; set; }
        public string BAOGAOYUEDU { get; set; }
        public string GONHZUOSHIJIAN { get; set; }
        public string ZONGSHIJIAN { get; set; }
        public string BEIZHU { get; set; }
        public string TIAOXINGMA { get; set; }
    }
}
