//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGONGZUOSHICHANG
    {
        public string ID { get; set; }
        public string WEITUODANWEI { get; set; }
        public string ZHENGSHUDANWEI { get; set; }
        public string SHOULIDANWEI { get; set; }
        public string QIJUMINGCHENG { get; set; }
        public string QIJUXINGHAO { get; set; }
        public string QIJUGUIGE { get; set; }
        public string CHUCHANGBIANHAO { get; set; }
        public Nullable<decimal> SHULIANG { get; set; }
        public string ZHENGSHUBAOGAOBIANHAO { get; set; }
        public string SHIYANSHI { get; set; }
        public string JIANDINGXIAOZHUNYUAN { get; set; }
        public string HEYANYUAN { get; set; }
        public Nullable<System.DateTime> SONGJIANRIQI { get; set; }
        public Nullable<System.DateTime> SHIYANSHIJIESHOUSHIJIAN { get; set; }
        public Nullable<System.DateTime> SHENHERIQI { get; set; }
        public Nullable<System.DateTime> SHENGPIRIQI { get; set; }
        public string BEIZHU { get; set; }
    }
}
