//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VQIJULINGQU2
    {
        public string ID { get; set; }
        public string APPLIANCE_NAME { get; set; }
        public string VERSION { get; set; }
        public string FACTORY_NUM { get; set; }
        public Nullable<decimal> NUM { get; set; }
        public string ATTACHMENT { get; set; }
        public string NAME { get; set; }
        public string APPLIANCE_RECIVE { get; set; }
        public string REPORTNUMBER { get; set; }
        public string REMARKS { get; set; }
        public string ORDER_TASK_INFORMATIONID { get; set; }
        public string APPLIANCECOLLECTIONSATE { get; set; }
        public string REPORTTORECEVESTATE { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
    }
}
