//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRUKU
    {
        public string ID { get; set; }
        public string REPORTNUMBER { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string APPLIANCE_NAME { get; set; }
        public string VERSION { get; set; }
        public string FACTORY_NUM { get; set; }
        public string CERTIFICATE_ENTERPRISE { get; set; }
        public string CUSTOMER_SPECIFIC_REQUIREMENTS { get; set; }
        public string NAME { get; set; }
        public string ORDER_STATUS { get; set; }
        public string STORAGEINSTRUCTIONS { get; set; }
        public string UNDERTAKE_LABORATORYID { get; set; }
        public Nullable<System.DateTime> APPROVALDATE { get; set; }
        public string STORAGEINSTRUCTI_STATU { get; set; }
        public string REPORTSTATUS { get; set; }
        public string REPORTSTATUSZI { get; set; }
        public string EQUIPMENT_STATUS_VALUUMN { get; set; }
    }
}
