//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRULE
    {
        public string ID { get; set; }
        public string NAMEOTHER { get; set; }
        public string NAME { get; set; }
        public string SCHEME_MENU { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string IS_UNCERTAINTY { get; set; }
        public string UNCERTAINTY_MENU { get; set; }
        public string UNDERTAKE_LABORATORYID { get; set; }
        public string INPUTSTATE { get; set; }
        public string PARENTID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string SCHEMEID { get; set; }
    }
}
