//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTEST_ITE
    {
        public decimal RID { get; set; }
        public string ROW_FLAG { get; set; }
        public string PREPARE_SCHEMEID { get; set; }
        public string SCHEMEID { get; set; }
        public string RULEID { get; set; }
        public string INPUTSTATE { get; set; }
        public string NAMEOTHER { get; set; }
        public string NAME { get; set; }
        public string SCHEME_MENU { get; set; }
        public string ID { get; set; }
        public string CONCLUSION { get; set; }
        public string HTMLVALUE { get; set; }
        public string REMARK { get; set; }
        public string ISCOMPLETE { get; set; }
        public string SCHEME_RULEID { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string PARENTID { get; set; }
    }
}
