//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VXIANGQING
    {
        public Nullable<decimal> ID { get; set; }
        public string DD { get; set; }
        public string ORDER_TASK_INFORMATIONID { get; set; }
        public string APPLIANCE_NAME { get; set; }
        public string STATE { get; set; }
        public string RECEIVEINS { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
