//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VZHENGSHULEIBEITONGJIFENXI
    {
        public string ID { get; set; }
        public string SUOSHUDANWEI { get; set; }
        public string ZHENGSHUDANWEI { get; set; }
        public string SHOULIDANWEI { get; set; }
        public string PIZHUNJIELUN { get; set; }
        public Nullable<System.DateTime> PIZHUNSHIJIAN { get; set; }
        public string SHOUQUANZIZHI { get; set; }
        public string ZHENGSHULEIBIE { get; set; }
        public string BAOGAOLEIBIE { get; set; }
        public Nullable<decimal> BAOGAOSHULIANG { get; set; }
    }
}
