//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSHIYANSHIGONGZUO
    {
        public string ID { get; set; }
        public Nullable<decimal> WEITUODAN { get; set; }
        public Nullable<decimal> JIANDINGWANCHENG { get; set; }
        public Nullable<decimal> SHEBEIGUZHANG { get; set; }
        public Nullable<decimal> PIZHUNTONGGUO { get; set; }
        public Nullable<decimal> HEGE { get; set; }
        public Nullable<decimal> BUHEGE { get; set; }
        public Nullable<decimal> CHAOQI { get; set; }
    }
}
