
--
-- VXIANGQING
--
CREATE OR REPLACE FORCE VIEW "VXIANGQING" 
  AS 
  select ROWNUM as ID
,a.ID dd--器具明细ID
,b.ID ORDER_TASK_INFORMATIONID--委托单ID
,a.APPLIANCE_NAME--器具名称
,'' REPORTNUMBER--报告编号
,CASE  
    WHEN g.APPLIANCECOLLECTIONSATE IS NULL 
    THEN '未领取'     
    ELSE g.APPLIANCECOLLECTIONSATE
 END AS STATE   --器具领取状态
,g.RECEIVEINS--器具领取单
,g.CREATEPERSON--领取人
,g.CREATETIME--领取时间

from APPLIANCE_DETAIL_INFORMATION a--器具明细
left join  ORDER_TASK_INFORMATION b--委托单
on b.id=a.ORDER_TASK_INFORMATIONID
left join APPLIANCECOLLECTION g--器具领取
on a.id=g.APPLIANCE_DETAIL_INFORMATIONID
union
select ROWNUM  as ID
,d.ID dd--器具明细ID
,b.ID APPLIANCE_DETAIL_INFORMATIONID--委托单ID
,a.APPLIANCE_NAME --器具名称
,d.REPORTNUMBER REPORTNUMBER--报告编号
,CASE  
    WHEN f.REPORTTORECEVESTATE IS NULL 
    THEN '未领取'     
    ELSE f.REPORTTORECEVESTATE
 END STATE    --报告领取状态
,f.RECEIVEREPORT--报告领取单 
,f.CREATEPERSON--领取人
,f.CREATETIME--领取时间

from PREPARE_SCHEME d--预备方案
left join REPORTCOLLECTION f--报告领取
on d.ID=f.PREPARE_SCHEMEID
left join APPLIANCE_LABORATORY c--器具明细信息_承接实验室
on d.ID=c.PREPARE_SCHEMEID
left join  APPLIANCE_DETAIL_INFORMATION a--器具明细
on c.APPLIANCE_DETAIL_INFORMATIONID=a.ID
left join ORDER_TASK_INFORMATION  b--委托单
on b.ID=a.ORDER_TASK_INFORMATIONID;
