INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'数表三相', N'数表三相', NULL, NULL, NULL,NULL);
INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'数表单相', N'数表单相', NULL, NULL, NULL,NULL);
INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'电能', N'电能', NULL, NULL, NULL,NULL);
INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'指示仪表', N'指示仪表', NULL, NULL, NULL,NULL);
INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'直流仪器', N'直流仪器', NULL, NULL, NULL,NULL);
INSERT INTO"UNDERTAKE_LABORATORY" ("ID", "NAME", "CREATETIME", "CREATEPERSON", "UPDATETIME", "UPDATEPERSON") VALUES (N'互感器', N'互感器', NULL, NULL, NULL,NULL);