--delete from SCHEME_RULE where 1=1
--delete from PROJECTTEMPLET where 1=1
--delete from SCHEME where 1=1
--delete from RULE where 1=1
--delete from QUALIFIED_UNQUALIFIED_TEST_ITE where 1=1
--update PREPARE_SCHEME set SCHEMEID='16100702025723755353249195bcb' where 1=1


--JJG 315-1983 直流数字电压表试行检定规程
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987','JJG(航天) 38-1987 直流标准电流源检定规程','JJG(航天) 38-1987 直流标准电流源检定规程',null,1,'否',null,'数表三相',null,null,null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_1','外观检查','外观检查',null,1,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_2','直流电流输出','直流电流输出 ','/PROJECTTEMPLET/ZhiLiuDianLiuShuChu',2,'是',null,'数表三相','ZhiLiuDianLiuShuChu','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_3','短期稳定度的测试','短期稳定度的测试',null,3,'否',null,'数表三相','WBK','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_4','线性误差','线性误差 ',null,4,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_5','负载调整率','负载调整率 ',null,5,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_6','分辨力','分辨力 ',null,6,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_7','电源调整率','电源调整率 ',null,7,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_8','纹波和噪声电压','纹波和噪声电压 ',null,8,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('38-1987_9','共模干扰抑制能力','共模干扰抑制能力 ',null,9,'否',null,'数表三相','HGBHG','38-1987',null,null,null,null);

--JJG 315-1983 直流数字电压表试行检定规程
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983','JJG 315-1983 直流数字电压表试行检定规程','JJG 315-1983 直流数字电压表试行检定规程 ',null,2,'否',null,'数表三相',null,null,null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_1','外观检查','外观检查 ',null,1,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_2','直流电压测量','直流电压测量 ',null,2,'否',null,'数表三相',null,'315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_2_1','非正负极性-相对误差-单相','直流电流输出 ','/PROJECTTEMPLET/ZhiLiuDianLiuDianYaFeiZhengFu',1,'是',null,'数表三相','ZhiLiuDianLiuDianYaFeiZhengFu','315-1983_2',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_2_2','非正负极性-相对误差-多通道','直流电流输出 ','/PROJECTTEMPLET/ZhiLiuDianLiuDianYaFeiZhengFu',2,'是',null,'数表三相','ZhiLiuDianLiuDianYaFeiZhengFu','315-1983_2',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_3','稳定误差','稳定误差 ',null,3,'否',null,'数表三相','WBK','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_4','线性误差','线性误差 ',null,4,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_5','显示能力','显示能力 ',null,5,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_6','分辨力','分辨力 ',null,6,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_7','温度系数','温度系数 ',null,7,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);
Insert into RULE (ID,NAMEOTHER,NAME,SCHEME_MENU,SORT,IS_UNCERTAINTY,UNCERTAINTY_MENU,UNDERTAKE_LABORATORYID,INPUTSTATE,PARENTID,CREATETIME,CREATEPERSON,UPDATETIME,UPDATEPERSON) values ('315-1983_8','电源电压变化的影响','电源电压变化的影响 ',null,8,'否',null,'数表三相','HGBHG','315-1983',null,null,null,null);

select * from RULE