--获取预备方案检测项目
create view VTEST_ITE
as
select P.ID as PREPARE_SCHEMEID,P.SCHEMEID as SCHEMEID, R.ID as RULEID,R.NAMEOTHER,R.NAME,R.SCHEME_MENU
,Q.ID,Q.CONCLUSION,Q.HTMLVALUE,Q.REMARK,NVL2(Q.ID,'已做','未做') as ISComplete  
from 
PREPARE_SCHEME P left join SCHEME_RULE S on P.SCHEMEID=S.SCHEMEID 
left join RULE R on S.RULEID=R.ID
left join QUALIFIED_UNQUALIFIED_TEST_ITE Q on P.ID=Q.PREPARE_SCHEMEID
and S.RULEID=Q.RULEID
where P.SCHEMEID=S.SCHEMEID 
-------------------