
--
-- SCHEME
--
  CREATE TABLE "SCHEME" 
   (	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"NAME" VARCHAR2(200),
	"REPORT_CATEGORY" VARCHAR2(200),
	"CERTIFICATE_CATEGORY" VARCHAR2(200),
	"STATUS" VARCHAR2(200),
	"ISSTOP" VARCHAR2(200),
	"ISPUBLISH" VARCHAR2(200),
	"COPYID" VARCHAR2(36),
	"UNDERTAKE_LABORATORYID" VARCHAR2(36),
	"PUBLISHTIME" DATE,
	"PUBLISHPERSON" VARCHAR2(200),
	"ISPUBLISHTIME" VARCHAR2(200),
	"ISPUBLISHPERSON" VARCHAR2(200),
	"CREATETIME" DATE,
	"CREATEPERSON" VARCHAR2(200),
	"UPDATETIME" DATE,
	"UPDATEPERSON" VARCHAR2(200),
	CONSTRAINT "PK_SCHEME" PRIMARY KEY ("ID") ENABLE
   );
--
-- FK_SCHEME_REFERENCE_UNDERTAK
--
ALTER TABLE "SCHEME" ADD CONSTRAINT "FK_SCHEME_REFERENCE_UNDERTAK" FOREIGN KEY ("UNDERTAKE_LABORATORYID") REFERENCES "UNDERTAKE_LABORATORY"("ID") ENABLE;

